apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacluster-deployment
  labels:
    app: hacluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hacluster
  template:
    metadata:
      labels:
        app: hacluster
    spec:
      containers:
      - name: hacluster
        image: dimilan/hacluster:v1.0
        ports:
        - containerPort: 80
